[workspace]
resolver = "2"

members = [
    "contracts/token_52f",
    "contracts/dampener_vault",
    "contracts/prize_pool",
]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"  # Optimized for size (WASM)
